version: "3"
services:
  www:
    build: ./Front/app/Dockerfile
    ports: 
      - "80:80"
    volumes: 
      - ./Front/app /usr/share/nginx/html
    links: 
      - node
    networks:
      - default
  web:
    build: 
      - ./Back/app_back/Dockerfile
    ports: 
      - "3000:3000"
    networks:
      - default
  